server {
  listen 80;
  server_name localhost;

  root /var/www/star/api/www;

  index index.php index.html index.htm;

  charset utf-8;

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location = /favicon.ico { access_log off; log_not_found off; }
  location = /robots.txt  { access_log off; log_not_found off; }

  location ~ \.php$ {
    fastcgi_pass app:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    include fastcgi_params;

    fastcgi_param HTTP_X_FORWARDED_HOST $host;
    fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
  }

  location ~ /\.(?!well-known).* {
    deny all;
  }
}